% test_vo_new_block_standalone.m
clear; clc; clear functions;
run('drone_params.m');

fprintf('Testing vo_new_block standalone (simulating 2s at 1kHz)...\n\n');
omega = circle_speed / circle_radius;

for k = 1:2000
    t_sim  = k * Ts;
    angle  = omega * t_sim;
    pos_k  = [circle_radius*cos(angle); circle_radius*sin(angle); circle_alt];
    euler_k = [0; 0; angle];

    [pos_vo, euler_vo, vo_valid, num_vis] = vo_new_block(...
        pos_k, euler_k, ...
        cam_fx, cam_fy, cam_cx, cam_cy, ...
        frame_width, frame_height, ...
        blob_radius, blob_sigma, ...
        min_depth, max_depth, ...
        orb_num_points, orb_num_levels, orb_scale_factor, ...
        klt_block_size(1), klt_block_size(2), ...
        klt_max_iterations, klt_num_levels, klt_max_error, ...
        ransac_max_distance, ransac_confidence, ransac_max_iterations, ...
        kf_min_features, kf_max_translation, kf_max_rotation, ...
        min_baseline, vo_update_hz, Ts, ...
        landmarks_3D, num_landmarks, R_cam_body);

    if mod(k,200) == 0
        err = norm(pos_vo - pos_k);
        fprintf('t=%5.2fs  valid=%d  map=%d  pos=[%6.2f,%6.2f,%6.2f]  err=%.3fm\n', ...
            t_sim, vo_valid, num_vis, pos_vo(1),pos_vo(2),pos_vo(3), err);
    end
end

fprintf('\nStandalone test complete.\n');